name: Area selection
type: boilerplate
regex: |
  ^\[[ \w]\] +Docs
  \[[ \w]\] +Installation
  \[[ \w]\] +Networking
  \[[ \w]\] +Performance and Scalability
  \[[ \w]\] +Extensions and Telemetry
  \[[ \w]\] +Security
  \[[ \w]\] +Test and Release
  \[[ \w]\] +User Experience
  \[[ \w]\] +Developer Infrastructure
  \[[ \w]\] +Upgrade
